"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path

import dj_database_url


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

# Values come from environment variables (set in docker-compose.yml).
# The defaults are only for local development.

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-26rvzq+5ipn76#wpyql*2+=mnm)iuakc2xtxltk=416ycfysif',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1',
).split(',')

CSRF_TRUSTED_ORIGINS = []

# Render sets this to the public hostname, e.g. taskflow.onrender.com
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

# Hugging Face Spaces sets this, e.g. muskanerum-taskflow.hf.space
SPACE_HOST = os.environ.get('SPACE_HOST')

for public_host in (RENDER_EXTERNAL_HOSTNAME, SPACE_HOST):
    if public_host:
        ALLOWED_HOSTS.append(public_host)
        CSRF_TRUSTED_ORIGINS.append(f'https://{public_host}')
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My app
    'tasks',

    # Django REST Framework
    'rest_framework',

    # CORS
    'corsheaders',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    # Serves static files and the built React app in production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS middleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Hugging Face shows the app inside an iframe on huggingface.co,
# so the "deny iframes" protection has to be off there.
if SPACE_HOST:
    MIDDLEWARE.remove('django.middleware.clickjacking.XFrameOptionsMiddleware')


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'config.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# DATABASE - POSTGRESQL
# =========================================================

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.environ.get('POSTGRES_DB', 'task_db'),

        'USER': os.environ.get('POSTGRES_USER', 'postgres'),

        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),

        'HOST': os.environ.get('POSTGRES_HOST', 'db'),

        'PORT': os.environ.get('POSTGRES_PORT', '5432'),

    }
}

# On Render the database comes as a single DATABASE_URL
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.parse(
        os.environ['DATABASE_URL'],
        conn_max_age=600,
    )


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# The built React app (copied here by Dockerfile.prod).
# WhiteNoise serves it at the site root, so "/" opens the frontend.
FRONTEND_DIST = BASE_DIR / 'frontend_dist'

if FRONTEND_DIST.exists():
    WHITENOISE_ROOT = FRONTEND_DIST
    WHITENOISE_INDEX_FILE = True


# =========================================================
# REST FRAMEWORK
# =========================================================

# The API has no login yet, so session authentication (and its
# CSRF check) is turned off. Otherwise being logged into /admin/
# would block create/update/delete requests from the frontend.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# =========================================================
# CORS
# =========================================================

CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
).split(',')


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'